import { Router } from 'express';
import authRouter        from './auth.routes';
import contactRouter     from './contact.routes';
import dealRouter        from './deal.routes';
import activityRouter    from './activity.routes';
import dashboardRouter   from './dashboard.routes';
import organizationRouter from './organization.routes';
import invitationRouter  from './invitation.routes';
import userRouter        from './user.routes';
import fileRouter        from './file.routes';
import notificationRouter from './notification.routes';
import leadRouter        from './lead.routes';
import companyRouter     from './company.routes';
import followUpRouter    from './followup.routes';
import timelineRouter    from './timeline.routes';
import emailTrackingRouter from './emailtracking.routes';
import quoteRouter       from './quote.routes';
import invoiceRouter     from './invoice.routes';
import contractRouter    from './contract.routes';
import salesOrderRouter  from './salesorder.routes';
import salesTargetRouter from './salestarget.routes';
import commissionRouter  from './commission.routes';
import campaignRouter    from './campaign.routes';
import couponRouter      from './coupon.routes';
import referralRouter    from './referral.routes';
import ticketRouter      from './ticket.routes';
import knowledgeRouter   from './knowledge.routes';
import slaRouter         from './sla.routes';
import projectRouter     from './project.routes';
import projectTaskRouter from './projecttask.routes';
import timeEntryRouter   from './timeentry.routes';
import departmentRouter       from './department.routes';
import employeeRouter         from './employee.routes';
import attendanceRouter       from './attendance.routes';
import leaveRouter            from './leave.routes';
import employeeDocumentRouter from './employeedocument.routes';
import employeeExitRouter     from './employeeexit.routes';
import payrollRouter          from './payroll.routes';
import jobPostingRouter       from './jobposting.routes';
import applicationRouter      from './application.routes';
import interviewRouter        from './interview.routes';
import offerLetterRouter      from './offerletter.routes';
import performanceRouter      from './performance.routes';
import promotionRouter        from './promotion.routes';
import trainingRouter         from './training.routes';
import expenseRouter          from './expense.routes';
import incomeRouter           from './income.routes';
import budgetRouter           from './budget.routes';
import bankAccountRouter      from './bankaccount.routes';
import taxRateRouter          from './taxrate.routes';
import productRouter          from './product.routes';
import productCategoryRouter  from './productcategory.routes';
import warehouseRouter        from './warehouse.routes';
import stockMovementRouter    from './stockmovement.routes';
import vendorRouter           from './vendor.routes';
import purchaseRequestRouter  from './purchaserequest.routes';
import rfqRouter              from './rfq.routes';
import purchaseOrderRouter    from './purchaseorder.routes';
import assetRouter            from './asset.routes';
import assetMaintenanceRouter from './assetmaintenance.routes';
import documentRouter         from './document.routes';
import calendarRouter         from './calendar.routes';
import chatRouter             from './chat.routes';
import announcementRouter     from './announcement.routes';
import appNotificationRouter  from './appnotification.routes';
import approvalRouter         from './approval.routes';
import workflowRouter         from './workflow.routes';
import securityRouter         from './security.routes';
import auditLogRouter         from './auditlog.routes';
import brandRouter            from './brand.routes';
import branchRouter           from './branch.routes';
import subscriptionRouter     from './subscription.routes';

const router = Router();

router.use('/auth',         authRouter);
router.use('/contacts',     contactRouter);
router.use('/deals',        dealRouter);
router.use('/activities',   activityRouter);
router.use('/dashboard',    dashboardRouter);
router.use('/organization', organizationRouter);
router.use('/invitations',  invitationRouter);
router.use('/users',        userRouter);
router.use('/files',        fileRouter);
router.use('/notifications', notificationRouter);
router.use('/leads',        leadRouter);
router.use('/companies',    companyRouter);
router.use('/follow-ups',   followUpRouter);
router.use('/timeline',     timelineRouter);
router.use('/email-trackings', emailTrackingRouter);
router.use('/',             quoteRouter);
router.use('/',             invoiceRouter);
router.use('/',             contractRouter);
router.use('/sales-orders', salesOrderRouter);
router.use('/sales-targets', salesTargetRouter);
router.use('/commissions',  commissionRouter);
router.use('/campaigns',    campaignRouter);
router.use('/coupons',      couponRouter);
router.use('/referrals',    referralRouter);
router.use('/tickets',      ticketRouter);
router.use('/knowledge-articles', knowledgeRouter);
router.use('/sla-policies', slaRouter);
router.use('/projects',     projectRouter);
router.use('/project-tasks', projectTaskRouter);
router.use('/time-entries', timeEntryRouter);
router.use('/departments',     departmentRouter);
router.use('/employees',       employeeRouter);
router.use('/attendance',      attendanceRouter);
router.use('/leaves',          leaveRouter);
router.use('/employee-documents', employeeDocumentRouter);
router.use('/employee-exits',  employeeExitRouter);
router.use('/payroll',         payrollRouter);
router.use('/job-postings',    jobPostingRouter);
router.use('/applications',    applicationRouter);
router.use('/interviews',      interviewRouter);
router.use('/offer-letters',   offerLetterRouter);
router.use('/performance-reviews', performanceRouter);
router.use('/promotions',      promotionRouter);
router.use('/training',        trainingRouter);
router.use('/expenses',        expenseRouter);
router.use('/incomes',         incomeRouter);
router.use('/budgets',         budgetRouter);
router.use('/bank-accounts',   bankAccountRouter);
router.use('/tax-rates',       taxRateRouter);
router.use('/products',        productRouter);
router.use('/product-categories', productCategoryRouter);
router.use('/warehouses',      warehouseRouter);
router.use('/stock-movements', stockMovementRouter);
router.use('/vendors',         vendorRouter);
router.use('/purchase-requests', purchaseRequestRouter);
router.use('/rfqs',            rfqRouter);
router.use('/purchase-orders', purchaseOrderRouter);
router.use('/assets',          assetRouter);
router.use('/asset-maintenance', assetMaintenanceRouter);
router.use('/documents',       documentRouter);
router.use('/',                approvalRouter);
router.use('/',                workflowRouter);
router.use('/calendar-events', calendarRouter);
router.use('/chat',            chatRouter);
router.use('/announcements',   announcementRouter);
router.use('/app-notifications', appNotificationRouter);
router.use('/security',        securityRouter);
router.use('/audit-logs',      auditLogRouter);
router.use('/brands',          brandRouter);
router.use('/branches',        branchRouter);
router.use('/subscription',    subscriptionRouter);

export default router;
